language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial

services:
  - redis-server

install:
  - pip install tox-travis coveralls

script:
  - tox

after_success:
  - coveralls

cache:
  directories:
    - $HOME/.cache/pip
